### ISSUE TITLE
AssetLib entry: can't use "master" as download hash

### ISSUE THREAD

**Issue by akien-mga** [oniksan/godobuf#1]
Hi there,

There's a slight issue with [your submission](https://godotengine.org/asset-library/asset/edit/608) on Godot's Asset Library as it uses "master" as download hash, but this changes everytime you push a commit and will thus invalidate the SHA256 sum we store to validate the download.

It would be better to use a commit hash, or a tag for version 0.2.2. You can edit the submission on https://godotengine.org/asset-library/asset/edit/608

**Comment by oniksan** [comment]
Done
