### ISSUE TITLE
oneof fields with default values get ignored when packed

### ISSUE THREAD

**Issue by wooky** [oniksan/godobuf#14]
Consider a message like this:
```proto
message Test {
  oneof foo {
    uint32 field1 = 1;
    uint32 field2 = 2;
  }
}
```
If I set field1 to 0, which is a default value in proto3, and pack the message, the result is empty. However, I should expect the packed data to include that field1 is set, that it's set to 0, and that field2 is unset.

**Comment by oniksan** [comment]
I'll check.

**Comment by wooky** [comment]
I decided to investigate this myself. The specifications only talk about _parsing_ files, but not about _writing_ them. I've written a small C++ program to see how the official library deals with it, using the protobuf file I posted above:
```cpp
#include <iomanip>
#include "footest.pb.h"

int main()
{
    FooTest fooTest;
    fooTest.set_field1(0);

    std::string output = fooTest.SerializeAsString();
    for (char c : output) {
        std::cout << std::hex << std::setfill('0') << std::setw(2) << (int)c << " ";
    }
    std::cout << '\n';
}
```

The output is "08 00", and changing to set_field2 gives "10 00". So the official way does set a value for the oneof, even if it's the default.

If you'd like, I can submit a PR that fixes this issue.

**Comment by oniksan** [comment]
Please tell me which version of protobuf you are using 2 or 3?

**Comment by wooky** [comment]
Version 3 only. Did not test with 2.

**Comment by oniksan** [comment]
In reference realisation on C++ if you just use simple int32 (not oneof) and set it to 0, which data are generated?

**Comment by oniksan** [comment]
Sorry. I was wrong, I'll fix it.
For oneof fields there is an exception to the serialization rules for default values:

> If you set a oneof field to the default value (such as setting an int32 oneof field to 0), the "case" of that oneof field will be set, and the value will be serialized on the wire.
