### ISSUE TITLE
Services and packages

### ISSUE THREAD

**Issue by lucroch** [oniksan/godobuf#20]
The addon is amazing, is it still in development? 
Are services and packages planned to come on next updates? If not, do you think it's possible? (In case I decide to fork and attempt to work on it)

**Comment by oniksan** [comment]
Hi, lucroch, thanks.
Updates are spontaneous or at the request of users.
There is no specific development plan.
If something specific needs to be added, then write here.
Perhaps there will be some development, while I myself do not know...
