### ISSUE TITLE
Add command line generation/auto generation

### ISSUE THREAD

**Issue by kelteseth** [oniksan/godobuf#29]
Protobuf files are used to be shared between multiple projects. For example, I have a CMake/C++ based server that generates the Protobuf c++ files, if I change the content of my messages.proto. For Godot, I have to do it manually and often simply forget to do it. It would be handy to automatically convert the protofile on change (like CMake does) or a way on how to trigger it externally via a command line tool.

**Comment by oniksan** [comment]
The existing functionality does not suit you?
![image](https://user-images.githubusercontent.com/36218761/161530706-e4b7725f-db42-4ca4-8363-0da98b7c4c91.png)

**Comment by kelteseth** [comment]
> The existing functionality does not suit you? ![image](https://user-images.githubusercontent.com/36218761/161530706-e4b7725f-db42-4ca4-8363-0da98b7c4c91.png)

Oh sorry looks like I missed this 😅
