### ISSUE TITLE
is it possible to support Any type?

### ISSUE THREAD

**Issue by lzy1g1225** [oniksan/godobuf#4]

**Comment by oniksan** [comment]
Hi.
To implement support Any must select the serialization method for the Godobuf. In Godobuf, as I understand it, there is no standard class (object) serialization method.
In addition, Google’s specification itself (https://developers.google.com/protocol-buffers/docs/proto3#any) states that "Currently the runtime libraries for working with Any types are under development."
How compatibility of unpacking between different platforms should be ensured is not clear to me either.

If you can clearly and formally describe how this should look, then I can try to implement support for Any.

**Comment by oniksan** [comment]
Due to the lack of answers to the questions posed - I close issue. If offers appear, open a new issue.
