### ISSUE TITLE
Could oneof be improved to determine the type besides the if else?

### ISSUE THREAD

**Issue by draicor** [oniksan/godobuf#49]
First of all, I really love this plugin, amazing work! I was wondering if this could somehow be improved or some advice on how I could approach the following problem.

Take this proto3 file:

```
syntax = "proto3";

option go_package = "pkg/packets";

// Packet types
message Chat { string text = 1; }
message ClientId { uint64 id = 1; } // For when the server sends a client its ID

// Packet container
message Packet {
  uint64 sender_id = 1;
  oneof payload { // Generates a field called Payload of type isPacket_Payload interface in Golang
    Chat chat_message = 2;
    ClientId client_id = 3;
  }
}
```

In my main.go file:
```
func main() {
	// I create a Packet
	packet := &packets.Packet{
		SenderId: 1,
		Payload:  packets.NewChatMessage("Hello, world"), // Helper function to avoid boilerplate code
	}
	
	// Determines the type of payload at runtime
	switch packet.GetPayload().(type) {
	case *packets.Packet_ChatMessage:
		fmt.Println("Its a chat message.")
	case *packets.Packet_ClientId:
		fmt.Println("It's a client ID message.")
	case nil:
		fmt.Println("The payload was not set.")
	default:
		fmt.Println("Invalid payload.")
	}
```
	
In this example, the console will print "Its a chat message." because its inferring the type of payload (oneof) using the .(type) from Golang. I saw on the readme that the way to do this in Godot with this plugin is to just do:

```
func _ready() -> void:
	if new_packet.has_chat_message():
		pass
	elif new_packet.has_client_id():
		pass
	else:
		pass
```
		
If I end up having 50 different "packet types", not only is more verbose, the code will have to check all of them to get to packet_type #50 for example.. Is there a more efficient way to do this? I mean I could add an enum that has the same packet_types and use that enum with a MATCH in godot to filter what to do, in fact I could probably use both, the enum with the MATCH plus the has_X_packet to double check that someone didn't make a mistake assigning the enum on packet creation, but its extra bytes sent over the network, I wish there was a more efficient way to do this, like Golang having the .(type) built into it.

**Comment by oniksan** [comment]
Hi!
As far as I remember, only this feature is implemented in Godobuf, everything is as you described.
There is nothing stopping you from using enum, it is just 1 additional byte to message if their number is less than 128.
I think the size of your messages is significantly larger than message type indicator.

**Comment by draicor** [comment]
Hey sir! I see, I'll use an enum then, was just wondering if it was a good approach, now that you mention the size you are totally right, thanks for replying back 😄
