### ISSUE TITLE
Support for typed GDScript

### ISSUE THREAD

**Issue by flyingpimonster** [oniksan/godobuf#5]
GDScript now supports optional types. This feature helps with code readability and maintainability, and it also improves code completion in the editor. It would be great if Godobuf added types to its generated code (in function parameters and return values) to take advantage of this feature.

**Comment by oniksan** [comment]
Already thinking about it ...
Not enough time yet ... I'll keep it on mind

**Comment by jakobwinkler** [comment]
Hey, I'm using godobuf in my current project and I too would like to have the type annotations generated. If you're okay with it @oniksan I'll implement it and send a pull request in the next couple of days.

**Comment by oniksan** [comment]
Are you already writing code? If not, then do not write, I will do it myself.

**Comment by jakobwinkler** [comment]
I had a look through the code yesterday and wanted to get started tonight. I'm fine with it either way. Let me know if I can help.

**Comment by oniksan** [comment]
I'll try to fix it myself today or tomorrow. If I don’t have time, I will write to you.

**Comment by jakobwinkler** [comment]
Great, thanks!

**Comment by oniksan** [comment]
Done: https://github.com/oniksan/godobuf/releases/tag/v0.4.0
If there will be bugs write to me.
